- name: Test
  hosts: all
  gather_facts: true
  sources:
    - name: range
      ansible.eda.range:
        limit: 5

  rules:
      actions:  
        - print_event:
            pretty: true    
        - set_fact: 
          fact:
            test_fact: "hello_world"
        - set_fact: 
          fact:
            test_fact2: "test - {{ test_fact }}"
